const data = {
  products: [
    {
      name: "adidas slime shirt",
      slug: "nike-slime-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 8,
      description: "new color shirt",
    },

    {
      name: "nike slime shoes",
      slug: "nike-red-shoes",
      category: "shoes",
      image: "./images/p2.jpg",
      price: 140,
      countInStock: 8,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "apple white shoes",
      slug: "apple-white-shoes",
      category: "apple",
      image: "./images/p3.jpg",
      price: 170,
      countInStock: 10,
      brand: "apple",
      rating: 4.5,
      numReviews: 10,
      description: "best quality shoes",
    },

    {
      name: "adidas black shoes",
      slug: "adidas-black-shirt",
      category: "shirts",
      image: "./images/p4.jpg",
      price: 200,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality shoes",
    },
    {
      name: "adidas black shoes",
      slug: "adidas-black-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 150,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality shoes",
    },
    {
      name: "adidas black shoes",
      slug: "adidas-black-shirt",
      category: "shirts",
      image: "./images/p2.jpg",
      price: 755,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality shoes",
    },
    {
      name: "adidas black shoes",
      slug: "adidas-black-shirt",
      category: "shirts",
      image: "./images/p4.jpg",
      price: 320,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality shoes",
    },
    {
      name: "adidas black shoes",
      slug: "adidas-black-shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 500,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality shoes",
    },
  ],
};

export default data;
